### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [seohyeon-lee-2025/mlh-allin-hack-2023#8]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by ghost** [comment]
Please assign this task to me as a part of WOB24 Contribution. I am a newbie and would like to take part in this campaign. A small effort to make meaningful contributions. @Emmarie-Ahtunan @KshitizRana @seohyeonlee2020 Thank you

**Comment by Emmarie-Ahtunan** [comment]
You've been assigned, @KiranBaliga. Thank you.

**Comment by ghost** [comment]
@Emmarie-Ahtunan @KshitizRana @seohyeonlee2020 Please review the PR and share the feedback. Please add level1 and WOB24 labels to the issue/PR. Thank you 🙏
